version: '3'
services:
  rest:
    build: .
    image: latex-microservice
    ports:
      - "80:80"
    environment:
      # port 80 is actually already defined as default for docker as ENV in Dockerfile
      - MICRONAUT_SERVER_PORT=80
      - INSTALL_PACKAGES=12many a2ping