version: '3'
services:
  rest:
    build: .
    image: latex-microservice
    ports:
      - "80:80"
    environment:
      # port 80 is actually already defined as default for docker as ENV in Dockerfile
      - MICRONAUT_SERVER_PORT=80
      - INSTALL_PACKAGES=12many a2ping#      # enable health check if Consul is used
#      - CONSUL_CLIENT_HEALTH_CHECK=true
#      # register this service on Consul
#      - CONSUL_CLIENT_REGISTRATION_ENABLED=true
#      # search for services on Consul
#      - CONSUL_CLIENT_DISCOVERY_ENABLED=true
#      # Consul server
#      - CONSUL_HOST=localhost
#      - CONSUL_PORT=8500

#  # Service registration and discovery with Consul
#  consul:
#    image: consul:1.8.0
#    ports:
#      - "8500:8500"